---
deployment:
  tasks:
    - export DEPLOYPATH=/home/abdelhak/public_html/myresume
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp portfolio-details $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH